Repository pytti-tools/pytti-core, pull requests merged in 2022-04, with the labels that each got.

#100 added use_tensorboard config option
  src/pytti/ImageGuide.py
  src/pytti/Transforms.py
  src/pytti/assets/default.yaml
  src/pytti/config/structured_config.py
  src/pytti/warmup.py
  src/pytti/workhorse.py
  tests/config/default.yaml
  tests/test_animation_broken.py
Labels: enhancement

#112 set restore from params
  src/pytti/workhorse.py
Labels: bug

#110 refactor loss configuration setup phase
  src/pytti/ImageGuide.py
  src/pytti/LossAug/DepthLossClass.py
  src/pytti/LossAug/LossOrchestratorClass.py
  src/pytti/LossAug/__init__.py
  src/pytti/Notebook.py
  src/pytti/rotoscoper.py
  src/pytti/workhorse.py
Labels: refactor

#111 VQGANImage refactoring
  src/pytti/Image/VQGANImage.py
Labels: refactor
